/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebSearchRouteImport } from './routes/api/web-search'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime-session'
import { Route as ApiReadPageRouteImport } from './routes/api/read-page'
import { Route as ApiLocalVaultRouteImport } from './routes/api/local-vault'
import { Route as ApiLocalModelsRouteImport } from './routes/api/local-models'
import { Route as ApiLocalChatRouteImport } from './routes/api/local-chat'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiFxRouteImport } from './routes/api/fx'
import { Route as ApiFreeChatRouteImport } from './routes/api/free-chat'
import { Route as ApiFindVideoRouteImport } from './routes/api/find-video'
import { Route as ApiEmbedRouteImport } from './routes/api/embed'
import { Route as ApiCritiqueRouteImport } from './routes/api/critique'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBuilderRouteImport } from './routes/api/builder'
import { Route as ApiAgentRouteImport } from './routes/api/agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebSearchRoute = ApiWebSearchRouteImport.update({
  id: '/api/web-search',
  path: '/api/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime-session',
  path: '/api/realtime-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadPageRoute = ApiReadPageRouteImport.update({
  id: '/api/read-page',
  path: '/api/read-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalVaultRoute = ApiLocalVaultRouteImport.update({
  id: '/api/local-vault',
  path: '/api/local-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalModelsRoute = ApiLocalModelsRouteImport.update({
  id: '/api/local-models',
  path: '/api/local-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalChatRoute = ApiLocalChatRouteImport.update({
  id: '/api/local-chat',
  path: '/api/local-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFxRoute = ApiFxRouteImport.update({
  id: '/api/fx',
  path: '/api/fx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFreeChatRoute = ApiFreeChatRouteImport.update({
  id: '/api/free-chat',
  path: '/api/free-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFindVideoRoute = ApiFindVideoRouteImport.update({
  id: '/api/find-video',
  path: '/api/find-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedRoute = ApiEmbedRouteImport.update({
  id: '/api/embed',
  path: '/api/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCritiqueRoute = ApiCritiqueRouteImport.update({
  id: '/api/critique',
  path: '/api/critique',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderRoute = ApiBuilderRouteImport.update({
  id: '/api/builder',
  path: '/api/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/critique': typeof ApiCritiqueRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/find-video': typeof ApiFindVideoRoute
  '/api/free-chat': typeof ApiFreeChatRoute
  '/api/fx': typeof ApiFxRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/local-chat': typeof ApiLocalChatRoute
  '/api/local-models': typeof ApiLocalModelsRoute
  '/api/local-vault': typeof ApiLocalVaultRoute
  '/api/read-page': typeof ApiReadPageRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/critique': typeof ApiCritiqueRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/find-video': typeof ApiFindVideoRoute
  '/api/free-chat': typeof ApiFreeChatRoute
  '/api/fx': typeof ApiFxRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/local-chat': typeof ApiLocalChatRoute
  '/api/local-models': typeof ApiLocalModelsRoute
  '/api/local-vault': typeof ApiLocalVaultRoute
  '/api/read-page': typeof ApiReadPageRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/critique': typeof ApiCritiqueRoute
  '/api/embed': typeof ApiEmbedRoute
  '/api/find-video': typeof ApiFindVideoRoute
  '/api/free-chat': typeof ApiFreeChatRoute
  '/api/fx': typeof ApiFxRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/local-chat': typeof ApiLocalChatRoute
  '/api/local-models': typeof ApiLocalModelsRoute
  '/api/local-vault': typeof ApiLocalVaultRoute
  '/api/read-page': typeof ApiReadPageRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent'
    | '/api/builder'
    | '/api/chat'
    | '/api/critique'
    | '/api/embed'
    | '/api/find-video'
    | '/api/free-chat'
    | '/api/fx'
    | '/api/generate-image'
    | '/api/local-chat'
    | '/api/local-models'
    | '/api/local-vault'
    | '/api/read-page'
    | '/api/realtime-session'
    | '/api/transcribe'
    | '/api/web-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent'
    | '/api/builder'
    | '/api/chat'
    | '/api/critique'
    | '/api/embed'
    | '/api/find-video'
    | '/api/free-chat'
    | '/api/fx'
    | '/api/generate-image'
    | '/api/local-chat'
    | '/api/local-models'
    | '/api/local-vault'
    | '/api/read-page'
    | '/api/realtime-session'
    | '/api/transcribe'
    | '/api/web-search'
  id:
    | '__root__'
    | '/'
    | '/api/agent'
    | '/api/builder'
    | '/api/chat'
    | '/api/critique'
    | '/api/embed'
    | '/api/find-video'
    | '/api/free-chat'
    | '/api/fx'
    | '/api/generate-image'
    | '/api/local-chat'
    | '/api/local-models'
    | '/api/local-vault'
    | '/api/read-page'
    | '/api/realtime-session'
    | '/api/transcribe'
    | '/api/web-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiBuilderRoute: typeof ApiBuilderRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCritiqueRoute: typeof ApiCritiqueRoute
  ApiEmbedRoute: typeof ApiEmbedRoute
  ApiFindVideoRoute: typeof ApiFindVideoRoute
  ApiFreeChatRoute: typeof ApiFreeChatRoute
  ApiFxRoute: typeof ApiFxRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiLocalChatRoute: typeof ApiLocalChatRoute
  ApiLocalModelsRoute: typeof ApiLocalModelsRoute
  ApiLocalVaultRoute: typeof ApiLocalVaultRoute
  ApiReadPageRoute: typeof ApiReadPageRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiWebSearchRoute: typeof ApiWebSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-search': {
      id: '/api/web-search'
      path: '/api/web-search'
      fullPath: '/api/web-search'
      preLoaderRoute: typeof ApiWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-session': {
      id: '/api/realtime-session'
      path: '/api/realtime-session'
      fullPath: '/api/realtime-session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/read-page': {
      id: '/api/read-page'
      path: '/api/read-page'
      fullPath: '/api/read-page'
      preLoaderRoute: typeof ApiReadPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-vault': {
      id: '/api/local-vault'
      path: '/api/local-vault'
      fullPath: '/api/local-vault'
      preLoaderRoute: typeof ApiLocalVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-models': {
      id: '/api/local-models'
      path: '/api/local-models'
      fullPath: '/api/local-models'
      preLoaderRoute: typeof ApiLocalModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-chat': {
      id: '/api/local-chat'
      path: '/api/local-chat'
      fullPath: '/api/local-chat'
      preLoaderRoute: typeof ApiLocalChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fx': {
      id: '/api/fx'
      path: '/api/fx'
      fullPath: '/api/fx'
      preLoaderRoute: typeof ApiFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/free-chat': {
      id: '/api/free-chat'
      path: '/api/free-chat'
      fullPath: '/api/free-chat'
      preLoaderRoute: typeof ApiFreeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/find-video': {
      id: '/api/find-video'
      path: '/api/find-video'
      fullPath: '/api/find-video'
      preLoaderRoute: typeof ApiFindVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed': {
      id: '/api/embed'
      path: '/api/embed'
      fullPath: '/api/embed'
      preLoaderRoute: typeof ApiEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/critique': {
      id: '/api/critique'
      path: '/api/critique'
      fullPath: '/api/critique'
      preLoaderRoute: typeof ApiCritiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder': {
      id: '/api/builder'
      path: '/api/builder'
      fullPath: '/api/builder'
      preLoaderRoute: typeof ApiBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiBuilderRoute: ApiBuilderRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCritiqueRoute: ApiCritiqueRoute,
  ApiEmbedRoute: ApiEmbedRoute,
  ApiFindVideoRoute: ApiFindVideoRoute,
  ApiFreeChatRoute: ApiFreeChatRoute,
  ApiFxRoute: ApiFxRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiLocalChatRoute: ApiLocalChatRoute,
  ApiLocalModelsRoute: ApiLocalModelsRoute,
  ApiLocalVaultRoute: ApiLocalVaultRoute,
  ApiReadPageRoute: ApiReadPageRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiWebSearchRoute: ApiWebSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
