/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime-session'
import { Route as ApiFxRouteImport } from './routes/api/fx'
import { Route as ApiFreeChatRouteImport } from './routes/api/free-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBuilderRouteImport } from './routes/api/builder'
import { Route as ApiAgentRouteImport } from './routes/api/agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime-session',
  path: '/api/realtime-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFxRoute = ApiFxRouteImport.update({
  id: '/api/fx',
  path: '/api/fx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFreeChatRoute = ApiFreeChatRouteImport.update({
  id: '/api/free-chat',
  path: '/api/free-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderRoute = ApiBuilderRouteImport.update({
  id: '/api/builder',
  path: '/api/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/free-chat': typeof ApiFreeChatRoute
  '/api/fx': typeof ApiFxRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/free-chat': typeof ApiFreeChatRoute
  '/api/fx': typeof ApiFxRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/builder': typeof ApiBuilderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/free-chat': typeof ApiFreeChatRoute
  '/api/fx': typeof ApiFxRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent'
    | '/api/builder'
    | '/api/chat'
    | '/api/free-chat'
    | '/api/fx'
    | '/api/realtime-session'
    | '/api/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent'
    | '/api/builder'
    | '/api/chat'
    | '/api/free-chat'
    | '/api/fx'
    | '/api/realtime-session'
    | '/api/transcribe'
  id:
    | '__root__'
    | '/'
    | '/api/agent'
    | '/api/builder'
    | '/api/chat'
    | '/api/free-chat'
    | '/api/fx'
    | '/api/realtime-session'
    | '/api/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiBuilderRoute: typeof ApiBuilderRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFreeChatRoute: typeof ApiFreeChatRoute
  ApiFxRoute: typeof ApiFxRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-session': {
      id: '/api/realtime-session'
      path: '/api/realtime-session'
      fullPath: '/api/realtime-session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fx': {
      id: '/api/fx'
      path: '/api/fx'
      fullPath: '/api/fx'
      preLoaderRoute: typeof ApiFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/free-chat': {
      id: '/api/free-chat'
      path: '/api/free-chat'
      fullPath: '/api/free-chat'
      preLoaderRoute: typeof ApiFreeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder': {
      id: '/api/builder'
      path: '/api/builder'
      fullPath: '/api/builder'
      preLoaderRoute: typeof ApiBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiBuilderRoute: ApiBuilderRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFreeChatRoute: ApiFreeChatRoute,
  ApiFxRoute: ApiFxRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
